#!/bin/bash

echo -e   "========= current branches ==========\n"

git branch # this will print all the branch options

echo -e "\n== which one do you want to test? ===\n"

read branch

git co $branch src/easy-button.js
git reset HEAD src/easy-button.js
git co $branch src/easy-button.css
git reset HEAD src/easy-button.css

echo -e "\n==========================\n"
echo    "   starting localhost:8080    "
echo -e "\n==========================\n"

python -m SimpleHTTPServer 8080

